const express = require("express");
const mongoose = require("mongoose");
const Product = require("../models/Product");
const Category = require("../models/Category");
const Review = require("../models/Review");
const User = require("../models/User");
const Profile = require("../models/Profile");
const { uploadSingle, uploadMultiple } = require("../middleware/upload");
const verifyToken = require("../middleware/authMiddleware");
const roleCheck = require("../middleware/roleMiddleware");
const cloudinary = require("cloudinary").v2;

const router = express.Router();

// Middleware to check if user is approved seller
const isApprovedSeller = async (req, res, next) => {
    try {
        const user = await User.findById(req.user.id);
        if (user.role === "admin") return next();
        if (user.role !== "seller_approved") {
            return res.status(403).json({
                message: "Access denied. Complete seller verification to add products."
            });
        }
        next();
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
};

router.post("/", verifyToken, isApprovedSeller, async (req, res) => {
    try {
        const { name, description, price, stock, category, tags, salePrice, featured, images } = req.body;
        const sellerId = req.user.id;

        console.log("=== PRODUCT CREATION DEBUG ===");
        console.log("User ID:", sellerId);
        console.log("Images received:", images);
        console.log("Type of images:", typeof images);
        console.log("Is array:", Array.isArray(images));
        console.log("=== END DEBUG ===");

        // Validate required fields
        if (!name || !description || !price || !stock || !category) {
            return res.status(400).json({ message: "Missing required fields" });
        }

        // Validate images
        if (!images || !Array.isArray(images) || images.length === 0) {
            return res.status(400).json({
                message: "No images provided",
                imagesReceived: images
            });
        }

        const categoryExists = await Category.findById(category);
        if (!categoryExists) return res.status(400).json({ message: "Invalid category" });

        const tagsArray = tags
            ? Array.isArray(tags)
                ? tags
                : tags.split(",").map(t => t.trim())
            : [];

        // Create product with images from request body
        const product = new Product({
            name,
            description,
            price,
            stock,
            category,
            images: images,
            tags: tagsArray,
            salePrice,
            featured: featured || false,
            seller: sellerId,
        });

        console.log("Product to save:", product);
        await product.save();

        // Create default review
        const defaultReview = new Review({
            product: product._id,
            user: sellerId,
            rating: 1,
            comment: "New product - awaiting customer reviews",
            isAutoGenerated: true,
        });
        await defaultReview.save();

        product.numReviews = 1;
        product.averageRating = 1;
        await product.save();

        res.status(201).json({
            message: "Product created successfully",
            product
        });
    } catch (err) {
        console.error("PRODUCT CREATION ERROR:", err);
        console.error("Error stack:", err.stack);
        res.status(500).json({
            message: "Server error",
            error: err.message,
            stack: process.env.NODE_ENV === 'development' ? err.stack : undefined
        });
    }
});

// Get all products with filters
router.get("/", async (req, res) => {
    try {
        const { category, search, minPrice, maxPrice, status, featured } = req.query;
        let filter = {};

        if (category && category !== 'all') filter.category = category;
        if (status && status !== 'all') filter.status = status;
        if (featured && featured !== 'all') filter.featured = featured === 'true';

        if (search) {
            filter.$or = [
                { name: { $regex: search, $options: 'i' } },
                { description: { $regex: search, $options: 'i' } },
                { tags: { $in: [new RegExp(search, 'i')] } }
            ];
        }

        if (minPrice || maxPrice) {
            filter.price = {};
            if (minPrice) filter.price.$gte = parseFloat(minPrice);
            if (maxPrice) filter.price.$lte = parseFloat(maxPrice);
        }

        const products = await Product.find(filter)
            .populate("category", "name")
            .populate("seller", "name email")
            .sort({ createdAt: -1 });

        res.json({ products, total: products.length });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Get product by category
router.get("/category/:id", async (req, res) => {
    try {
        const products = await Product.find({ category: req.params.id })
            .populate("category", "name")
            .populate("seller", "name email")
            .sort({ createdAt: -1 });

        res.json({ products, total: products.length });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Get single product by ID
router.get("/:id", async (req, res) => {
    try {
        const product = await Product.findById(req.params.id)
            .populate("category", "name")
            .populate("seller", "name email");

        if (!product) return res.status(404).json({ message: "Product not found" });

        res.json(product);
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Get seller's products
router.get("/seller/products", verifyToken, roleCheck(["seller", "admin"]), async (req, res) => {
    try {
        const sellerId = req.user.id;
        const products = await Product.find({ seller: sellerId })
            .populate("category", "name")
            .populate("seller", "name email")
            .sort({ createdAt: -1 });

        res.json({ products, total: products.length });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Admin: paginated products
router.get("/admin/products", verifyToken, roleCheck(["admin"]), async (req, res) => {
    try {
        const {
            page = 1,
            limit = 10,
            category,
            search,
            minPrice,
            maxPrice,
            status,
            featured,
            sortBy = 'createdAt',
            sortOrder = 'desc'
        } = req.query;

        let filter = {};
        if (category && category !== 'all') filter.category = category;
        if (status && status !== 'all') filter.status = status;
        if (featured && featured !== 'all') filter.featured = featured === 'true';

        if (search) {
            filter.$or = [
                { name: { $regex: search, $options: 'i' } },
                { description: { $regex: search, $options: 'i' } },
                { tags: { $in: [new RegExp(search, 'i')] } }
            ];
        }

        if (minPrice || maxPrice) {
            filter.price = {};
            if (minPrice) filter.price.$gte = parseFloat(minPrice);
            if (maxPrice) filter.price.$lte = parseFloat(maxPrice);
        }

        const sort = {};
        sort[sortBy] = sortOrder === 'asc' ? 1 : -1;

        const products = await Product.find(filter)
            .populate("category", "name")
            .populate("seller", "name email")
            .sort(sort)
            .limit(limit * 1)
            .skip((page - 1) * limit);

        const total = await Product.countDocuments(filter);

        res.json({
            products,
            totalPages: Math.ceil(total / limit),
            currentPage: page,
            total
        });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Bulk product actions (Admin only)
router.post("/admin/products/bulk-actions", verifyToken, roleCheck(["admin"]), async (req, res) => {
    try {
        const { productIds, action, data } = req.body;

        if (!productIds || !Array.isArray(productIds) || productIds.length === 0) {
            return res.status(400).json({ message: "Product IDs are required" });
        }

        let update = {};
        switch (action) {
            case 'activate':
                update = { status: 'active' };
                break;
            case 'deactivate':
                update = { status: 'inactive' };
                break;
            case 'feature':
                update = { featured: true };
                break;
            case 'unfeature':
                update = { featured: false };
                break;
            case 'update-stock':
                if (!data || !data.stock) {
                    return res.status(400).json({ message: "Stock value is required" });
                }
                update = { stock: parseInt(data.stock) };
                break;
            case 'delete':
                await Product.deleteMany({ _id: { $in: productIds } });
                return res.json({ message: `${productIds.length} products deleted` });
            default:
                return res.status(400).json({ message: "Invalid action" });
        }

        const result = await Product.updateMany(
            { _id: { $in: productIds } },
            update
        );

        res.json({
            message: `${result.modifiedCount} products updated`,
            modifiedCount: result.modifiedCount
        });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

router.get("/seller/:sellerId/count", async (req, res) => {
    try {
        const { sellerId } = req.params;

        // Validate sellerId
        if (!mongoose.Types.ObjectId.isValid(sellerId)) {
            return res.status(400).json({ message: "Invalid seller ID" });
        }

        // Check if seller exists and is approved
        const seller = await User.findById(sellerId);
        if (!seller || seller.role !== "seller_approved") {
            return res.status(404).json({ message: "Seller not found or not approved" });
        }

        const productCount = await Product.countDocuments({
            seller: sellerId,
            status: 'active' // Only count active products
        });

        res.json({
            productCount,
            sellerName: seller.name,
            storeName: seller.storeName
        });
    } catch (error) {
        console.error("Product count error:", error);
        res.status(500).json({ message: "Server error", error: error.message });
    }
});

// Get trending products
router.get("/trending/products", async (req, res) => {
    try {
        const limit = parseInt(req.query.limit) || 6;

        const trendingProducts = await Product.find({
            status: 'active',
            stock: { $gt: 0 }
        })
            .populate("category", "name")
            .populate("seller", "name storeName")
            .sort({
                averageRating: -1,     // Highest rated first
                numReviews: -1,        // Then by number of reviews
                createdAt: -1          // Then by most recent
            })
            .limit(limit);

        res.json({
            trendingProducts,
            total: trendingProducts.length
        });
    } catch (err) {
        console.error("Trending products error:", err);
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Get seller's public profile with product count
router.get("/seller/:sellerId/public-profile", async (req, res) => {
    try {
        const { sellerId } = req.params;

        // Validate sellerId
        if (!mongoose.Types.ObjectId.isValid(sellerId)) {
            return res.status(400).json({ message: "Invalid seller ID" });
        }

        // Check if seller exists and is approved
        const seller = await User.findById(sellerId).select("name email storeName storeDescription role");
        if (!seller || seller.role !== "seller_approved") {
            return res.status(404).json({ message: "Seller not found or not approved" });
        }

        // Get seller profile
        const profile = await Profile.findOne({ user: sellerId }).select(
            "businessType city yearsInBusiness mainProducts businessDescription profileImage"
        );

        // Get product count
        const productCount = await Product.countDocuments({
            seller: sellerId,
            status: 'active'
        });

        // Get active products count
        const activeProducts = await Product.countDocuments({
            seller: sellerId,
            status: 'active',
            stock: { $gt: 0 }
        });

        res.json({
            seller: {
                id: seller._id,
                name: seller.name,
                storeName: seller.storeName,
                storeDescription: seller.storeDescription,
                role: seller.role
            },
            profile: {
                businessType: profile?.businessType,
                city: profile?.city,
                yearsInBusiness: profile?.yearsInBusiness || 0,
                mainProducts: profile?.mainProducts || [],
                businessDescription: profile?.businessDescription,
                profileImage: profile?.profileImage
            },
            stats: {
                totalProducts: productCount,
                activeProducts: activeProducts
            }
        });
    } catch (error) {
        console.error("Seller public profile error:", error);
        res.status(500).json({ message: "Server error", error: error.message });
    }
});

// Update product with optional image upload
router.put("/:id", verifyToken, roleCheck(["seller", "admin"]), async (req, res) => {
    try {
        const { name, description, price, stock, category, tags, salePrice, featured, status, images } = req.body;

        console.log("=== PRODUCT UPDATE DEBUG ===");
        console.log("Raw images received:", images);
        console.log("=== END DEBUG ===");

        // Validate required fields
        if (!name || !description || !price || !stock || !category) {
            return res.status(400).json({ message: "Missing required fields" });
        }

        const categoryExists = await Category.findById(category);
        if (!categoryExists) return res.status(400).json({ message: "Invalid category" });

        // Process tags
        const tagsArray = tags
            ? Array.isArray(tags)
                ? tags
                : tags.split(",").map(t => t.trim())
            : [];

        // Clean images - remove _id field and handle mixed formats
        let cleanImages = [];
        if (images && Array.isArray(images)) {
            cleanImages = images.map(img => {
                // If it's an object with url
                if (img && typeof img === 'object' && img.url) {
                    return {
                        url: img.url,
                        publicId: img.publicId || null
                    };
                }
                // If it's a string
                if (typeof img === 'string') {
                    return {
                        url: img,
                        publicId: null
                    };
                }
                return null;
            }).filter(img => img !== null); // Remove null entries
        }

        console.log("Cleaned images:", cleanImages);

        // Create update data
        const updateData = {
            name,
            description,
            price: parseFloat(price),
            stock: parseInt(stock),
            category,
            images: cleanImages, // Use cleaned images
            tags: tagsArray,
            featured: featured || false,
            status: status || "active",
        };

        // Handle salePrice
        if (salePrice !== undefined && salePrice !== null && salePrice !== "") {
            updateData.salePrice = parseFloat(salePrice);
        }

        const product = await Product.findByIdAndUpdate(
            req.params.id,
            updateData,
            { new: true }
        );

        if (!product) return res.status(404).json({ message: "Product not found" });

        res.json({
            message: "Product updated successfully",
            product
        });
    } catch (err) {
        console.error("PRODUCT UPDATE ERROR:", err);
        console.error("Error details:", err.message);
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

router.delete("/:id", verifyToken, roleCheck(["seller", "admin"]), async (req, res) => {
    try {
        const productId = req.params.id;
        const userId = req.user.id;
        const user = await User.findById(userId);

        console.log("=== PRODUCT DELETE REQUEST ===");
        console.log("Product ID:", productId);
        console.log("User ID:", userId);
        console.log("User role:", user.role);
        console.log("=== END DEBUG ===");

        const product = await Product.findById(productId);

        if (!product) {
            return res.status(404).json({ message: "Product not found" });
        }

        // Check authorization: admin can delete any product, seller can only delete their own
        if (user.role !== "admin" && product.seller.toString() !== userId) {
            return res.status(403).json({
                message: "Not authorized to delete this product",
                productOwner: product.seller.toString(),
                currentUser: userId
            });
        }

        await Product.findByIdAndDelete(productId);

        res.json({
            message: "Product deleted successfully",
            productId: productId
        });
    } catch (err) {
        console.error("PRODUCT DELETE ERROR:", err);
        res.status(500).json({
            message: "Server error",
            error: err.message
        });
    }
});

module.exports = router;