const express = require("express");
const Review = require("../models/Review");
const Product = require("../models/Product");
const UserActivity = require("../models/userActivity");
const router = express.Router();
const verifyToken = require("../middleware/authMiddleware");
const roleCheck = require("../middleware/roleMiddleware");

// Add Review
router.post("/", verifyToken, async (req, res) => {
    try {
        const { productId, rating, comment } = req.body;
        const userId = req.user.id; // Get user from token

        const product = await Product.findById(productId);
        if (!product) {
            return res.status(404).json({ message: "Product not found" });
        }

        // Check if user purchased this product
        const userActivity = await UserActivity.findOne({ user: userId });
        if (!userActivity || !userActivity.purchasedProducts.includes(productId)) {
            return res.status(403).json({
                message: "You can only review products you've purchased"
            });
        }

        const existingReview = await Review.findOne({ product: productId, user: userId });
        if (existingReview) {
            return res.status(400).json({ message: "You have already reviewed this product" });
        }

        const review = new Review({
            product: productId,
            user: userId,
            rating,
            comment,
        });

        await review.save();

        res.status(201).json({
            message: "Review added successfully",
            review,
        });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// View all reviews of product
router.get("/:productId", async (req, res) => {
    try {
        const { productId } = req.params;

        const reviews = await Review.find({ product: productId })
            .populate("user", "name email")
            .sort({ isAutoGenerated: 1, createdAt: -1 }); // Show real reviews first

        if (reviews.length === 0) {
            return res.status(200).json({
                message: "No reviews for this product yet",
                totalReviews: 0,
                averageRating: 0,
                reviews: []
            });
        }

        // Filter out auto-generated reviews for average calculation
        const realReviews = reviews.filter(review => !review.isAutoGenerated);
        const avgRating = realReviews.length > 0
            ? realReviews.reduce((sum, review) => sum + review.rating, 0) / realReviews.length
            : 0;

        res.json({
            totalReviews: realReviews.length,
            averageRating: avgRating.toFixed(1),
            reviews: reviews.filter(review => !review.isAutoGenerated) // Only return real reviews
        });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

// Delete Review
router.delete("/:reviewId", verifyToken, roleCheck(["admin", "buyer"]), async (req, res) => {
    try {
        const { reviewId } = req.params;

        const review = await Review.findById(reviewId);
        if (!review) {
            return res.status(404).json({ message: "Review not found" });
        }

        await Review.findByIdAndDelete(reviewId);

        res.json({ message: "Review deleted successfully" });
    } catch (err) {
        res.status(500).json({ message: "Server error", error: err.message });
    }
});

module.exports = router;
